import { iColumnsOption } from "./interface";
/**
 * toolbar-常量
 * @author lllgn
 */

// 工具栏菜单
const barList: Array<iColumnsOption> = [
  {
    label: "表格项",
    type: "table",
    prop: "table",
    icon: "table",
    eidtOption: ["label", "prop"],
    addFormHide: true,
    editFormHide: true,
  },
  {
    label: "标题",
    type: "title",
    prop: "title",
    icon: "title",
    eidtOption: ["label", "prop", "hide", "editFormHide"],
  },
  {
    label: "输入框",
    type: "input",
    prop: "name",
    icon: "title",
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "placeholder",
      "sort",
      "help",
      "extra",
      "formItemWidth",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "showWordLimit",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
    width: 200,
    placeholder: "请输入",
  },
  {
    label: "数字框",
    type: "number",
    prop: "number",
    icon: "number",
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "mode",
      "placeholder",
      "step",
      "precision",
      "sort",
      "help",
      "extra",
      "formItemWidth",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "密码框",
    type: "password",
    prop: "password",
    icon: "password",
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "placeholder",
      "sort",
      "help",
      "extra",
      "formItemWidth",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "showWordLimit",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "文本域",
    type: "textarea",
    prop: "textarea",
    icon: "textarea",
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "placeholder",
      "sort",
      "help",
      "extra",
      "formItemWidth",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "showWordLimit",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "单选",
    type: "radio",
    prop: "radio",
    icon: "radio",
    dictData: [],
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "radioType",
      "direction",
      "sort",
      "help",
      "extra",
      "dictProps",
      "dictData",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "formItemWidth",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "多选",
    type: "checkbox",
    prop: "checkbox",
    icon: "checkbox",
    dictData: [],
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "sort",
      "help",
      "extra",
      "dictProps",
      "dictData",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "formItemWidth",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "下拉选择",
    type: "select",
    prop: "select",
    icon: "select",
    dictData: [],
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "multiple",
      "defaultInputValue",
      "placeholder",
      "sort",
      "help",
      "extra",
      "dictProps",
      "dictData",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "formItemWidth",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "开关",
    type: "switch",
    prop: "switch",
    icon: "switch",
    eidtOption: [],
  },
  {
    label: "级联选择",
    type: "cascader",
    prop: "cascader",
    icon: "cascader",
    dictData: [],
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "placeholder",
      "sort",
      "help",
      "extra",
      "dictProps",
      "dictData",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "formItemWidth",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
  {
    label: "日期",
    type: "date",
    prop: "date",
    icon: "date",
    eidtOption: [],
    children: [
      {
        label: "日期",
        type: "date",
        prop: "date",
        icon: "date",
        eidtOption: [
          "title_form",
          "label",
          "prop",
          "disabledDate",
          "showTime",
          "format",
          "placeholder",
          "sort",
          "help",
          "extra",
          "dictProps",
          "dictData",
          "rules",
          "slot",
          "hide",
          "disabled",
          "hideLabel",
          "hideAsterisk",
          "formItemWidth",
          "title_crud",
          "searchFormShow",
          "searchSlot",
          "searchSort",
          "searchWidth",
          "formSlot",
          "formSort",
          "addFormHide",
          "addDisabled",
          "editFormHide",
          "editDisabled",
        ],
      },
      {
        label: "年",
        type: "year",
        prop: "year",
        icon: "year",
        eidtOption: [
          "title_form",
          "label",
          "prop",
          "disabledDate",
          "showTime",
          "format",
          "placeholder",
          "sort",
          "help",
          "extra",
          "dictProps",
          "dictData",
          "rules",
          "slot",
          "hide",
          "disabled",
          "hideLabel",
          "hideAsterisk",
          "formItemWidth",
          "title_crud",
          "searchFormShow",
          "searchSlot",
          "searchSort",
          "searchWidth",
          "formSlot",
          "formSort",
          "addFormHide",
          "addDisabled",
          "editFormHide",
          "editDisabled",
        ],
      },
      {
        label: "月",
        type: "month",
        prop: "month",
        icon: "month",
        eidtOption: [
          "title_form",
          "label",
          "prop",
          "disabledDate",
          "showTime",
          "format",
          "placeholder",
          "sort",
          "help",
          "extra",
          "dictProps",
          "dictData",
          "rules",
          "slot",
          "hide",
          "disabled",
          "hideLabel",
          "hideAsterisk",
          "formItemWidth",
          "title_crud",
          "searchFormShow",
          "searchSlot",
          "searchSort",
          "searchWidth",
          "formSlot",
          "formSort",
          "addFormHide",
          "addDisabled",
          "editFormHide",
          "editDisabled",
        ],
      },
      {
        label: "周",
        type: "week",
        prop: "week",
        icon: "week",
        eidtOption: [
          "title_form",
          "label",
          "prop",
          "disabledDate",
          "showTime",
          "format",
          "placeholder",
          "sort",
          "help",
          "extra",
          "dictProps",
          "dictData",
          "rules",
          "slot",
          "hide",
          "disabled",
          "hideLabel",
          "hideAsterisk",
          "formItemWidth",
          "title_crud",
          "searchFormShow",
          "searchSlot",
          "searchSort",
          "searchWidth",
          "formSlot",
          "formSort",
          "addFormHide",
          "addDisabled",
          "editFormHide",
          "editDisabled",
        ],
      },
      {
        label: "季度",
        type: "quarter",
        prop: "quarter",
        icon: "quarter",
        eidtOption: [
          "title_form",
          "label",
          "prop",
          "disabledDate",
          "showTime",
          "format",
          "placeholder",
          "sort",
          "help",
          "extra",
          "dictProps",
          "dictData",
          "rules",
          "slot",
          "hide",
          "disabled",
          "hideLabel",
          "hideAsterisk",
          "formItemWidth",
          "title_crud",
          "searchFormShow",
          "searchSlot",
          "searchSort",
          "searchWidth",
          "formSlot",
          "formSort",
          "addFormHide",
          "addDisabled",
          "editFormHide",
          "editDisabled",
        ],
      },
      {
        label: "范围选择器",
        type: "range",
        prop: "range",
        icon: "range",
        eidtOption: [
          "title_form",
          "label",
          "prop",
          "disabledDate",
          "disabledTime",
          "showTime",
          "format",
          "placeholder",
          "sort",
          "help",
          "extra",
          "dictProps",
          "dictData",
          "rules",
          "slot",
          "hide",
          "disabled",
          "hideLabel",
          "hideAsterisk",
          "formItemWidth",
          "title_crud",
          "searchFormShow",
          "searchSlot",
          "searchSort",
          "searchWidth",
          "formSlot",
          "formSort",
          "addFormHide",
          "addDisabled",
          "editFormHide",
          "editDisabled",
        ],
      },
    ],
  },
  {
    label: "时间",
    type: "time",
    prop: "time",
    icon: "time",
    eidtOption: [
      "title_form",
      "label",
      "prop",
      "disabledHours",
      "disabledMinutes",
      "disabledSeconds",
      "use12Hours",
      "placeholder",
      "sort",
      "help",
      "extra",
      "dictProps",
      "dictData",
      "rules",
      "slot",
      "hide",
      "disabled",
      "hideLabel",
      "hideAsterisk",
      "formItemWidth",
      "title_crud",
      "searchFormShow",
      "searchSlot",
      "searchSort",
      "searchWidth",
      "formSlot",
      "formSort",
      "addFormHide",
      "addDisabled",
      "editFormHide",
      "editDisabled",
    ],
  },
];

export default {
  barList,
};
